### ISSUE TITLE
Problem with instaling

### ISSUE THREAD

**Issue by ghost** [Geequlim/godot-themes#10]
RESTART: C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\templaty\godot-themes-master\install.py 
Installing theme arc_dark to C:/Users/kajet/AppData/Roaming/Godot/theme
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\templaty\godot-themes-master\install.py", line 60, in <module>
    install(defaultdir)
  File "C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\templaty\godot-themes-master\install.py", line 48, in install
    handleFile(p, op, path)
  File "C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\templaty\godot-themes-master\install.py", line 34, in handleFile
    "res://addons", themdir, sys.maxint)
AttributeError: module 'sys' has no attribute 'maxint'

**Comment by Geequlim** [comment]
Fixed :)
